- name: Node exporter installation
  hosts: client,cluster
  become: true
  become_user: root
  tasks:
  - name: accept repo GPG key
    ansible.builtin.shell:
      cmd: rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
  - name: Install EPEL
    ansible.builtin.dnf:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      state: present
  - name: install node-exporter
    ansible.builtin.dnf:
      name: golang-github-prometheus-node-exporter
      state: latest
  - name: move service file
    ansible.builtin.copy:
      src: node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
      owner: root
      group: root
  - name: start node-exporter
    ansible.builtin.service:
      name: node_exporter
      state: started
      daemon_reload: true
  - name: open port 9100
    ansible.posix.firewalld:
      port: 9100/tcp
      permanent: true
      state: disabled
      zone: public
      immediate: true
